# Site
title: Brent Brinkley
description: Web Developer
url: http://brentbrinkley.com
logo: brent.png
locale: en_US

background:
    # this image will be shown on homepage's left block
    homepage: images/cover.jpg

    # this image will be shown on post list page
    post-list: images/background.png

    # this image will be shown when post's front matter doesn't specify any image
    default-post: images/unsplash-gallery-image-3.jpg

# Jekyll
permalink: /:title/
markdown: kramdown
highlighter: rouge
kramdown:
    auto_ids: true
    footnote_nr: 1
    entity_output: as_char
    toc_levels: 1..6
    enable_coderay: false

sass:
    sass_dir: assets/_sass
    style: compressed

# Google Analytics
#google-analytics: UA-XXXXX-Y

# Social Links
github: brentbrinkley
linkedin: brent-brinkley-21932435
#dribbble:          username
#youtube:           username
#codepen:           username

# Gems
gems:
    - jekyll-feed
    - jekyll-sitemap
    - jekyll-gist

# Exclude list
include: [_pages]
exclude:
    [
        README.md,
        Gemfile,
        Gemfile.lock,
        _site,
        src,
        vendor,
        CNAME,
        LICENSE,
        Rakefile,
        .sass-cache,
        .DS_Store,
    ]
